# ----------------------------------------------------------------------------
#
# Package             : PapaParse 
# Source Repo         : https://github.com/kishorkunal-raj/PapaParse
# Travis Job Link     : https://travis-ci.com/github/Siddhesh-Ghadi/sample-travis-job/builds/210384845
# Created travis.yml  : No
# Maintainer          : Kishor Kunal Raj <kishore.kunal.mr@ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------

arch:
  - amd64
  - ppc64le
  
dist: bionic

language: node_js
node_js:
  - "8"
  - "9"
  - "10"
  - "11"

